'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { Upload, Search, MessageSquare, Zap, Shield, Clock } from 'lucide-react';
import { BentoGrid, BentoGridItem } from '@/components/ui/bento-grid';
import { SpotlightCard } from '@/components/ui/spotlight-card';
import { cn } from '@/lib/utils';

const features = [
    {
        title: 'Smart Document Upload',
        description: 'Drag and drop PDFs, Word docs, and text files. Our AI processes and indexes everything automatically for instant retrieval.',
        icon: <Upload className="w-6 h-6 text-primary-400" />,
        header: (
            <div className="flex flex-col gap-2 w-full h-24 p-4 bg-dark-900/50 rounded-xl">
                <div className="flex items-center gap-2">
                    <div className="w-8 h-8 rounded-lg bg-primary-500/20 flex items-center justify-center">
                        <Upload className="w-4 h-4 text-primary-400" />
                    </div>
                    <span className="text-sm text-dark-300">Q4_Report.pdf</span>
                    <span className="text-xs text-green-400 ml-auto">✓ Indexed</span>
                </div>
                <div className="flex items-center gap-2">
                    <div className="w-8 h-8 rounded-lg bg-accent/20 flex items-center justify-center">
                        <Upload className="w-4 h-4 text-accent" />
                    </div>
                    <span className="text-sm text-dark-300">Research_Notes.docx</span>
                    <span className="text-xs text-green-400 ml-auto">✓ Indexed</span>
                </div>
            </div>
        ),
        className: 'md:col-span-2',
    },
    {
        title: 'Semantic Search',
        description: 'Find information by meaning, not just keywords. Our AI understands context and delivers exactly what you need.',
        icon: <Search className="w-6 h-6 text-accent" />,
        header: (
            <div className="w-full h-24 p-4 bg-dark-900/50 rounded-xl flex items-center justify-center">
                <div className="relative w-full max-w-xs">
                    <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-dark-500" />
                    <div className="w-full pl-10 pr-4 py-2 bg-dark-800 rounded-lg text-sm text-dark-400 border border-dark-700">
                        What are our Q4 revenue targets?
                    </div>
                </div>
            </div>
        ),
        className: 'md:col-span-1',
    },
    {
        title: 'AI-Powered Answers',
        description: 'Get accurate, contextual answers generated by advanced AI with source citations.',
        icon: <MessageSquare className="w-6 h-6 text-green-400" />,
        header: (
            <div className="w-full h-24 p-4 bg-dark-900/50 rounded-xl flex items-center">
                <div className="flex items-start gap-3">
                    <div className="w-8 h-8 rounded-full bg-green-500/20 flex items-center justify-center flex-shrink-0">
                        <Zap className="w-4 h-4 text-green-400" />
                    </div>
                    <p className="text-sm text-dark-300 line-clamp-3">
                        Based on page 12, the Q4 revenue target is $2.4M with expected growth of 18%...
                    </p>
                </div>
            </div>
        ),
        className: 'md:col-span-1',
    },
    {
        title: 'Enterprise Security',
        description: 'Your documents are encrypted and stored securely. Only you can access your knowledge base.',
        icon: <Shield className="w-6 h-6 text-blue-400" />,
        header: (
            <div className="w-full h-24 p-4 bg-dark-900/50 rounded-xl flex items-center justify-center">
                <div className="flex items-center gap-4">
                    <div className="w-12 h-12 rounded-xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center">
                        <Shield className="w-6 h-6 text-blue-400" />
                    </div>
                    <div className="text-left">
                        <p className="text-sm font-medium text-white">AES-256 Encrypted</p>
                        <p className="text-xs text-dark-400">SOC 2 Compliant</p>
                    </div>
                </div>
            </div>
        ),
        className: 'md:col-span-1',
    },
    {
        title: 'Lightning Fast',
        description: 'Get answers in milliseconds. Our vector search engine delivers instant results.',
        icon: <Clock className="w-6 h-6 text-yellow-400" />,
        header: (
            <div className="w-full h-24 p-4 bg-dark-900/50 rounded-xl flex items-center justify-center">
                <div className="text-center">
                    <p className="text-4xl font-bold text-yellow-400">0.3s</p>
                    <p className="text-xs text-dark-400 mt-1">Average response time</p>
                </div>
            </div>
        ),
        className: 'md:col-span-1',
    },
];

export function Features() {
    return (
        <section id="features" className="py-24 px-6 relative overflow-hidden">
            {/* Background gradient */}
            <div className="absolute inset-0 bg-gradient-to-b from-dark-900 to-dark-950" />
            <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[800px] h-[400px] bg-primary-500/5 rounded-full blur-[120px]" />

            <div className="relative z-10 max-w-7xl mx-auto">
                {/* Section Header */}
                <motion.div
                    className="text-center mb-16"
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.5 }}
                >
                    <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
                        Everything You Need to
                        <span className="block bg-gradient-to-r from-primary-400 to-accent bg-clip-text text-transparent">
                            Master Your Documents
                        </span>
                    </h2>
                    <p className="text-lg text-dark-400 max-w-2xl mx-auto">
                        Powerful features designed to transform how you interact with your knowledge base
                    </p>
                </motion.div>

                {/* Bento Grid */}
                <BentoGrid className="max-w-5xl mx-auto">
                    {features.map((feature, i) => (
                        <BentoGridItem
                            key={i}
                            title={feature.title}
                            description={feature.description}
                            header={feature.header}
                            icon={feature.icon}
                            className={feature.className}
                        />
                    ))}
                </BentoGrid>
            </div>
        </section>
    );
}

export default Features;
